version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sami606713/campusx_bot:frontend-latest  # Tag for the frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sami606713/campusx_bot:backend-latest  # Tag for the backend
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: always
    depends_on:
      - frontend
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}

networks:
  app_network:
    driver: bridge
