version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: always
    depends_on:
      - frontend
    env_file:
      - backend/.env
    # environment:
    #   - TAVILY_API_KEY={TAVILY_API_KEY}
    #   # - TAVILY_API_KEY=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
    #   - GROQ_API_KEY=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

networks:
  app_network:
    driver: bridge
